# Generated by Django 5.0.6 on 2024-06-29 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_numeber',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
