# Generated by Django 5.0.6 on 2024-06-29 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_patientprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_numeber',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\+d{10}$', code='invalid_phone_number', message='Enter a valid phone number in the format 9999999999.')]),
        ),
    ]
