# Generated by Django 5.0.6 on 2024-06-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_patientprofile_phone_numeber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='phone_numeber',
            new_name='phone_number',
        ),
    ]
