# Generated by Django 5.0.6 on 2024-06-29 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_phone_numeber_patientprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('/[2-9]{2}\\d{8}/', code='invalid_phone_number', message='Enter a valid phone number in the format 9999999999.')]),
        ),
    ]
