# Generated by Django 5.0.6 on 2024-06-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_patientprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
